apiVersion: v1
kind: PersistentVolume
metadata:
  name: #VOL_NAME#
  label:
    storage: #VOL_NAME#
spec:
  capacity:
    storage: 15Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: "#EXPORT_BASE#/#VOL_NAME#"
    server: "#NFS_SERVER#"
  persistentVolumeReclaimPolicy: Retain
